// Auto-generated by scripts/build-languages.mjs.
// Re-run that script to refresh. DO NOT edit by hand; your changes
// will be overwritten.
//
// Source: Wikifunctions Z60 catalogue. Generated 2026-04-19T15:44:10.243Z.
// Entries: 12 pinned (top of picker) + 507 alphabetical.
// RTL languages filtered out until the CSS pass for bidirectional layout.

export const LANGUAGES = [
  {
    "iso": "en",
    "native": "English",
    "english": "English",
    "wfZid": "Z1002"
  },
  {
    "iso": "de",
    "native": "Deutsch",
    "english": "German",
    "wfZid": "Z1430"
  },
  {
    "iso": "fr",
    "native": "français",
    "english": "French",
    "wfZid": "Z1004"
  },
  {
    "iso": "es",
    "native": "español",
    "english": "Spanish",
    "wfZid": "Z1003"
  },
  {
    "iso": "it",
    "native": "Italiano",
    "english": "Italian",
    "wfZid": "Z1787"
  },
  {
    "iso": "pt",
    "native": "português",
    "english": "Portuguese",
    "wfZid": "Z1037"
  },
  {
    "iso": "ru",
    "native": "русский",
    "english": "Russian",
    "wfZid": "Z1005"
  },
  {
    "iso": "ja",
    "native": "日本語",
    "english": "Japanese",
    "wfZid": "Z1830"
  },
  {
    "iso": "zh",
    "native": "中文",
    "english": "Chinese",
    "wfZid": "Z1006"
  },
  {
    "iso": "pl",
    "native": "polski",
    "english": "Polish",
    "wfZid": "Z1025"
  },
  {
    "iso": "nl",
    "native": "Nederlands",
    "english": "Dutch",
    "wfZid": "Z1157"
  },
  {
    "iso": "hi",
    "native": "हिन्दी",
    "english": "Hindi",
    "wfZid": "Z1820"
  },
  {
    "iso": "mul",
    "native": "📚🗣️🌍",
    "english": "multiple languages",
    "wfZid": "Z1360"
  },
  {
    "iso": "sma",
    "native": "åarjelsaemien",
    "english": "Southern Sami",
    "wfZid": "Z1738"
  },
  {
    "iso": "abq",
    "native": "Abaza",
    "english": "Abaza",
    "wfZid": "Z1196"
  },
  {
    "iso": "jac",
    "native": "Abꞌxubꞌal Poptiꞌ",
    "english": "Jakalteko",
    "wfZid": "Z1927"
  },
  {
    "iso": "agq",
    "native": "Aghem",
    "english": "Aghem",
    "wfZid": "Z1081"
  },
  {
    "iso": "akk",
    "native": "Akkadian",
    "english": "Akkadian",
    "wfZid": "Z1712"
  },
  {
    "iso": "sia",
    "native": "Akkala Sámi",
    "english": "Akkala Sámi",
    "wfZid": "Z1443"
  },
  {
    "iso": "bss",
    "native": "Akoose",
    "english": "Akoose",
    "wfZid": "Z1855"
  },
  {
    "iso": "akz",
    "native": "Alabama",
    "english": "Alabama",
    "wfZid": "Z1235"
  },
  {
    "iso": "smn",
    "native": "anarâškielâ",
    "english": "Inari Sami",
    "wfZid": "Z1352"
  },
  {
    "iso": "njo",
    "native": "Ao Naga",
    "english": "Ao Naga",
    "wfZid": "Z1594"
  },
  {
    "iso": "aro",
    "native": "Araona",
    "english": "Araona",
    "wfZid": "Z1359"
  },
  {
    "iso": "arp",
    "native": "Arapaho",
    "english": "Arapaho",
    "wfZid": "Z1638"
  },
  {
    "iso": "arw",
    "native": "Arawak",
    "english": "Arawak",
    "wfZid": "Z1313"
  },
  {
    "iso": "rup",
    "native": "armãneashti",
    "english": "Aromanian",
    "wfZid": "Z1097"
  },
  {
    "iso": "asa",
    "native": "Asu",
    "english": "Asu",
    "wfZid": "Z1743"
  },
  {
    "iso": "gn",
    "native": "Avañe'ẽ",
    "english": "Guarani",
    "wfZid": "Z1357"
  },
  {
    "iso": "ae",
    "native": "Avestan",
    "english": "Avestan",
    "wfZid": "Z1300"
  },
  {
    "iso": "ksf",
    "native": "Bafia",
    "english": "Bafia",
    "wfZid": "Z1033"
  },
  {
    "iso": "bfd",
    "native": "Bafut",
    "english": "Bafut",
    "wfZid": "Z1595"
  },
  {
    "iso": "bkc",
    "native": "Baka",
    "english": "Baka",
    "wfZid": "Z1801"
  },
  {
    "iso": "bax",
    "native": "Bamun",
    "english": "Bamun",
    "wfZid": "Z1792"
  },
  {
    "iso": "nan-latn",
    "native": "Bân-lâm-gú (Lô-má-jī)",
    "english": "Minnan (Latin script)",
    "wfZid": "Z1893"
  },
  {
    "iso": "nan-latn-tailo",
    "native": "Bân-lâm-gú (Tâi-lô)",
    "english": "Minnan (Tâi-lô)",
    "wfZid": "Z1922"
  },
  {
    "iso": "bci",
    "native": "Baoulé",
    "english": "Baoulé",
    "wfZid": "Z1016"
  },
  {
    "iso": "bug-latn",
    "native": "Basa Ugi",
    "english": "Buginese (Latin script)",
    "wfZid": "Z1909"
  },
  {
    "iso": "bas",
    "native": "Basaa",
    "english": "Basaa",
    "wfZid": "Z1485"
  },
  {
    "iso": "bbc-latn",
    "native": "Batak Toba",
    "english": "Batak Toba (Latin script)",
    "wfZid": "Z1676"
  },
  {
    "iso": "tji",
    "native": "bifzivsar",
    "english": "Northern Tujia",
    "wfZid": "Z1935"
  },
  {
    "iso": "bik",
    "native": "Bikol",
    "english": "Bikol",
    "wfZid": "Z1382"
  },
  {
    "iso": "bi",
    "native": "Bislama",
    "english": "Bislama",
    "wfZid": "Z1315"
  },
  {
    "iso": "byn",
    "native": "Blin",
    "english": "Blin",
    "wfZid": "Z1711"
  },
  {
    "iso": "zbl",
    "native": "Blissymbols",
    "english": "Blissymbols",
    "wfZid": "Z1588"
  },
  {
    "iso": "bzs",
    "native": "Brazilian Sign Language",
    "english": "Brazilian Sign Language",
    "wfZid": "Z1907"
  },
  {
    "iso": "bnn",
    "native": "Bunun",
    "english": "Bunun",
    "wfZid": "Z1606"
  },
  {
    "iso": "wes",
    "native": "Cameroon Pidgin",
    "english": "Cameroon Pidgin",
    "wfZid": "Z1073"
  },
  {
    "iso": "en-ca",
    "native": "Canadian English",
    "english": "Canadian English",
    "wfZid": "Z1437"
  },
  {
    "iso": "fr-ca",
    "native": "Canadian French",
    "english": "Canadian French",
    "wfZid": "Z1640"
  },
  {
    "iso": "rmc",
    "native": "Carpathian Romani",
    "english": "Carpathian Romani",
    "wfZid": "Z1215"
  },
  {
    "iso": "cay",
    "native": "Cayuga",
    "english": "Cayuga",
    "wfZid": "Z1635"
  },
  {
    "iso": "ceb",
    "native": "Cebuano",
    "english": "Cebuano",
    "wfZid": "Z1486"
  },
  {
    "iso": "shu",
    "native": "Chadian Arabic",
    "english": "Chadian Arabic",
    "wfZid": "Z1320"
  },
  {
    "iso": "chg",
    "native": "Chagatai",
    "english": "Chagatai",
    "wfZid": "Z1496"
  },
  {
    "iso": "chb",
    "native": "Chibcha",
    "english": "Chibcha",
    "wfZid": "Z1460"
  },
  {
    "iso": "cic",
    "native": "Chickasaw",
    "english": "Chickasaw",
    "wfZid": "Z1156"
  },
  {
    "iso": "clc",
    "native": "Chilcotin",
    "english": "Chilcotin",
    "wfZid": "Z1225"
  },
  {
    "iso": "lue",
    "native": "chiluvale",
    "english": "Chiluvale",
    "wfZid": "Z1926"
  },
  {
    "iso": "tum",
    "native": "chiTumbuka",
    "english": "Tumbuka",
    "wfZid": "Z1302"
  },
  {
    "iso": "chk",
    "native": "Chuukese",
    "english": "Chuukese",
    "wfZid": "Z1364"
  },
  {
    "iso": "nwc",
    "native": "Classical Newari",
    "english": "Classical Newari",
    "wfZid": "Z1198"
  },
  {
    "iso": "sei",
    "native": "Cmique Itom",
    "english": "Seri",
    "wfZid": "Z1799"
  },
  {
    "iso": "cjk",
    "native": "cokwe",
    "english": "Chokwe",
    "wfZid": "Z1895"
  },
  {
    "iso": "sw-cd",
    "native": "Congo Swahili",
    "english": "Congo Swahili",
    "wfZid": "Z1358"
  },
  {
    "iso": "cop",
    "native": "Coptic",
    "english": "Coptic",
    "wfZid": "Z1263"
  },
  {
    "iso": "el-cy",
    "native": "Cypriot Greek",
    "english": "Cypriot Greek",
    "wfZid": "Z1208"
  },
  {
    "iso": "dak",
    "native": "Dakota",
    "english": "Dakota",
    "wfZid": "Z1190"
  },
  {
    "iso": "dlc",
    "native": "Dalecarlian",
    "english": "Dalecarlian",
    "wfZid": "Z1292"
  },
  {
    "iso": "se",
    "native": "davvisámegiella",
    "english": "Northern Sami",
    "wfZid": "Z1519"
  },
  {
    "iso": "se-no",
    "native": "davvisámegiella (Norgga bealde)",
    "english": "Northern Sami (Norway)",
    "wfZid": "Z1871"
  },
  {
    "iso": "se-se",
    "native": "davvisámegiella (Ruoŧa bealde)",
    "english": "Northern Sami (Sweden)",
    "wfZid": "Z1872"
  },
  {
    "iso": "se-fi",
    "native": "davvisámegiella (Suoma bealde)",
    "english": "Northern Sami (Finland)",
    "wfZid": "Z1870"
  },
  {
    "iso": "dzg",
    "native": "Dazaga",
    "english": "Dazaga",
    "wfZid": "Z1674"
  },
  {
    "iso": "del",
    "native": "Delaware",
    "english": "Delaware",
    "wfZid": "Z1376"
  },
  {
    "iso": "ddn",
    "native": "dendi",
    "english": "Dendi",
    "wfZid": "Z1890"
  },
  {
    "iso": "de-x-formal",
    "native": "Deutsch (Sie-Form)‎",
    "english": "German (formal address)",
    "wfZid": "Z1231"
  },
  {
    "iso": "doi",
    "native": "Dogri",
    "english": "Dogri",
    "wfZid": "Z1209"
  },
  {
    "iso": "dgr",
    "native": "Dogrib",
    "english": "Dogrib",
    "wfZid": "Z1128"
  },
  {
    "iso": "dua",
    "native": "Duálá",
    "english": "Duala",
    "wfZid": "Z1442"
  },
  {
    "iso": "dtp",
    "native": "Dusun Bundu-liwan",
    "english": "Central Dusun",
    "wfZid": "Z1088"
  },
  {
    "iso": "crl",
    "native": "East Cree",
    "english": "East Cree",
    "wfZid": "Z1525"
  },
  {
    "iso": "bgp",
    "native": "Eastern Balochi",
    "english": "Eastern Balochi",
    "wfZid": "Z1659"
  },
  {
    "iso": "cjm",
    "native": "Eastern Cham",
    "english": "Eastern Cham",
    "wfZid": "Z1572"
  },
  {
    "iso": "cjm-arab",
    "native": "Eastern Cham (Arabic script)",
    "english": "Eastern Cham (Arabic script)",
    "wfZid": "Z1539"
  },
  {
    "iso": "cjm-cham",
    "native": "Eastern Cham (Cham script)",
    "english": "Eastern Cham (Cham script)",
    "wfZid": "Z1259"
  },
  {
    "iso": "cjm-latn",
    "native": "Eastern Cham (Latin script)",
    "english": "Eastern Cham (Latin script)",
    "wfZid": "Z1705"
  },
  {
    "iso": "ydd",
    "native": "Eastern Yiddish",
    "english": "Eastern Yiddish",
    "wfZid": "Z1399"
  },
  {
    "iso": "igb",
    "native": "Ebira",
    "english": "Ebira",
    "wfZid": "Z1920"
  },
  {
    "iso": "mh",
    "native": "Ebon",
    "english": "Marshallese",
    "wfZid": "Z1703"
  },
  {
    "iso": "etu",
    "native": "Ejagham",
    "english": "Ejagham",
    "wfZid": "Z1660"
  },
  {
    "iso": "eka",
    "native": "Ekajuk",
    "english": "Ekajuk",
    "wfZid": "Z1284"
  },
  {
    "iso": "elx",
    "native": "Elamite",
    "english": "Elamite",
    "wfZid": "Z1537"
  },
  {
    "iso": "vmw",
    "native": "emakhuwa",
    "english": "Makhuwa",
    "wfZid": "Z1873"
  },
  {
    "iso": "ebu",
    "native": "Embu",
    "english": "Embu",
    "wfZid": "Z1089"
  },
  {
    "iso": "es-formal",
    "native": "español (formal)‎",
    "english": "Spanish (formal)‎",
    "wfZid": "Z1423"
  },
  {
    "iso": "es-419",
    "native": "español de América Latina",
    "english": "Latin American Spanish",
    "wfZid": "Z1547"
  },
  {
    "iso": "eto",
    "native": "Eton",
    "english": "Eton",
    "wfZid": "Z1725"
  },
  {
    "iso": "pt-pt",
    "native": "European Portuguese",
    "english": "European Portuguese",
    "wfZid": "Z1294"
  },
  {
    "iso": "eu",
    "native": "euskara",
    "english": "Basque",
    "wfZid": "Z1314"
  },
  {
    "iso": "ewo",
    "native": "Ewondo",
    "english": "Ewondo",
    "wfZid": "Z1590"
  },
  {
    "iso": "fmp",
    "native": "Fe'Fe'",
    "english": "Fe'Fe'",
    "wfZid": "Z1847"
  },
  {
    "iso": "hif-latn",
    "native": "Fiji Hindi",
    "english": "Fiji Hindi (Latin script)",
    "wfZid": "Z1578"
  },
  {
    "iso": "hif",
    "native": "Fiji Hindi",
    "english": "Fiji Hindi",
    "wfZid": "Z1118"
  },
  {
    "iso": "fil",
    "native": "Filipino",
    "english": "Filipino",
    "wfZid": "Z1226"
  },
  {
    "iso": "rmf",
    "native": "Finnish Kalo",
    "english": "Finnish Kalo",
    "wfZid": "Z1707"
  },
  {
    "iso": "fo",
    "native": "føroyskt",
    "english": "Faroese",
    "wfZid": "Z1218"
  },
  {
    "iso": "gur",
    "native": "Frafra",
    "english": "Frafra",
    "wfZid": "Z1680"
  },
  {
    "iso": "frc",
    "native": "français cadien",
    "english": "Cajun French",
    "wfZid": "Z1334"
  },
  {
    "iso": "frm",
    "native": "françois",
    "english": "Middle French",
    "wfZid": "Z1245"
  },
  {
    "iso": "gv",
    "native": "Gaelg",
    "english": "Manx",
    "wfZid": "Z1627"
  },
  {
    "iso": "sm",
    "native": "Gagana Samoa",
    "english": "Samoan",
    "wfZid": "Z1144"
  },
  {
    "iso": "gd",
    "native": "Gàidhlig",
    "english": "Scottish Gaelic",
    "wfZid": "Z1339"
  },
  {
    "iso": "gl",
    "native": "galego",
    "english": "Galician",
    "wfZid": "Z1170"
  },
  {
    "iso": "kld",
    "native": "Gamilaraay",
    "english": "Gamilaraay",
    "wfZid": "Z1771"
  },
  {
    "iso": "mga",
    "native": "Gaoidhealg",
    "english": "Middle Irish",
    "wfZid": "Z1266"
  },
  {
    "iso": "aln",
    "native": "Gegë",
    "english": "Gheg Albanian",
    "wfZid": "Z1084"
  },
  {
    "iso": "gpe",
    "native": "GhaPE",
    "english": "Ghanaian Pidgin",
    "wfZid": "Z1877"
  },
  {
    "iso": "bbj",
    "native": "Ghomala",
    "english": "Ghomala",
    "wfZid": "Z1283"
  },
  {
    "iso": "gil",
    "native": "Gilbertese",
    "english": "Gilbertese",
    "wfZid": "Z1759"
  },
  {
    "iso": "gon",
    "native": "Gondi",
    "english": "Gondi",
    "wfZid": "Z1658"
  },
  {
    "iso": "gom-latn",
    "native": "Gõychi Konknni",
    "english": "Goan Konkani (Latin script)",
    "wfZid": "Z1192"
  },
  {
    "iso": "grb",
    "native": "Grebo",
    "english": "Grebo",
    "wfZid": "Z1268"
  },
  {
    "iso": "nrf-gg",
    "native": "Guernésiais",
    "english": "Guernésiais",
    "wfZid": "Z1169"
  },
  {
    "iso": "guw",
    "native": "gungbe",
    "english": "Gun",
    "wfZid": "Z1019"
  },
  {
    "iso": "guz",
    "native": "Gusii",
    "english": "Gusii",
    "wfZid": "Z1410"
  },
  {
    "iso": "hak-latn",
    "native": "Hak-kâ-ngî (Pha̍k-fa-sṳ)",
    "english": "Hakka (Latin script)",
    "wfZid": "Z1934"
  },
  {
    "iso": "cnh",
    "native": "Hakha-Chin",
    "english": "Hakha-Chin",
    "wfZid": "Z1080"
  },
  {
    "iso": "haz",
    "native": "Hazaragi",
    "english": "Hazaragi",
    "wfZid": "Z1492"
  },
  {
    "iso": "ho",
    "native": "Hiri Motu",
    "english": "Hiri Motu",
    "wfZid": "Z1415"
  },
  {
    "iso": "hit",
    "native": "Hittite",
    "english": "Hittite",
    "wfZid": "Z1487"
  },
  {
    "iso": "hmn",
    "native": "Hmong",
    "english": "Hmong",
    "wfZid": "Z1323"
  },
  {
    "iso": "hoc-latn",
    "native": "Ho",
    "english": "Ho (Latin script)",
    "wfZid": "Z1969"
  },
  {
    "iso": "nn-hognorsk",
    "native": "Høgnorsk",
    "english": "Høgnorsk",
    "wfZid": "Z1706"
  },
  {
    "iso": "igl",
    "native": "Igala",
    "english": "Igala",
    "wfZid": "Z1852"
  },
  {
    "iso": "en-x-piglatin",
    "native": "Igpay Atinlay",
    "english": "Pig Latin",
    "wfZid": "Z1881"
  },
  {
    "iso": "hil",
    "native": "Ilonggo",
    "english": "Hiligaynon",
    "wfZid": "Z1457"
  },
  {
    "iso": "en-in",
    "native": "Indian English",
    "english": "Indian English",
    "wfZid": "Z1966"
  },
  {
    "iso": "moe",
    "native": "Innu",
    "english": "Innu",
    "wfZid": "Z1520"
  },
  {
    "iso": "isv-latn",
    "native": "Interslavic (Latin script)",
    "english": "Interslavic (Latin script)",
    "wfZid": "Z1750"
  },
  {
    "iso": "ike-latn",
    "native": "inuktitut",
    "english": "Eastern Canadian Inuktitut (Latin script)",
    "wfZid": "Z1204"
  },
  {
    "iso": "ik",
    "native": "Iñupiak",
    "english": "Inupiaq",
    "wfZid": "Z1141"
  },
  {
    "iso": "bto",
    "native": "Iriga Bicolano",
    "english": "Iriga Bicolano",
    "wfZid": "Z1125"
  },
  {
    "iso": "zu",
    "native": "isiZulu",
    "english": "Zulu",
    "wfZid": "Z1330"
  },
  {
    "iso": "isu",
    "native": "Isu",
    "english": "Isu",
    "wfZid": "Z1673"
  },
  {
    "iso": "iba",
    "native": "Jaku Iban",
    "english": "Iban",
    "wfZid": "Z1449"
  },
  {
    "iso": "ja-hrkt",
    "native": "Japanese (Kana script)",
    "english": "Japanese (Kana script)",
    "wfZid": "Z1444"
  },
  {
    "iso": "dyo",
    "native": "Jola-Fonyi",
    "english": "Jola-Fonyi",
    "wfZid": "Z1733"
  },
  {
    "iso": "jpr",
    "native": "Judeo-Persian",
    "english": "Judeo-Persian",
    "wfZid": "Z1277"
  },
  {
    "iso": "jut",
    "native": "jysk",
    "english": "Jutish",
    "wfZid": "Z1068"
  },
  {
    "iso": "kbp",
    "native": "Kabɩyɛ",
    "english": "Kabiye",
    "wfZid": "Z1384"
  },
  {
    "iso": "kkj",
    "native": "Kako",
    "english": "Kako",
    "wfZid": "Z1833"
  },
  {
    "iso": "kln",
    "native": "Kalenjin",
    "english": "Kalenjin",
    "wfZid": "Z1428"
  },
  {
    "iso": "kam",
    "native": "Kamba",
    "english": "Kamba",
    "wfZid": "Z1603"
  },
  {
    "iso": "kbl",
    "native": "Kanembu",
    "english": "Kanembu",
    "wfZid": "Z1557"
  },
  {
    "iso": "pam",
    "native": "Kapampangan",
    "english": "Pampanga",
    "wfZid": "Z1609"
  },
  {
    "iso": "cak",
    "native": "Kaqchikel",
    "english": "Kaqchikel",
    "wfZid": "Z1027"
  },
  {
    "iso": "kai",
    "native": "Karai-karai",
    "english": "Karekare",
    "wfZid": "Z1912"
  },
  {
    "iso": "krl",
    "native": "karjal",
    "english": "Karelian",
    "wfZid": "Z1543"
  },
  {
    "iso": "csb",
    "native": "kaszëbsczi",
    "english": "Kashubian",
    "wfZid": "Z1665"
  },
  {
    "iso": "ckv",
    "native": "Kebalan",
    "english": "Kavalan",
    "wfZid": "Z1977"
  },
  {
    "iso": "sjk",
    "native": "Kemi Sámi",
    "english": "Kemi Sámi",
    "wfZid": "Z1201"
  },
  {
    "iso": "ken",
    "native": "Kenyang",
    "english": "Kenyang",
    "wfZid": "Z1041"
  },
  {
    "iso": "ker",
    "native": "Kera",
    "english": "Kera",
    "wfZid": "Z1142"
  },
  {
    "iso": "kha",
    "native": "Khasi",
    "english": "Khasi",
    "wfZid": "Z1264"
  },
  {
    "iso": "kho",
    "native": "Khotanese",
    "english": "Khotanese",
    "wfZid": "Z1566"
  },
  {
    "iso": "hav",
    "native": "Kihavu",
    "english": "Havu",
    "wfZid": "Z1968"
  },
  {
    "iso": "hke",
    "native": "kihunde",
    "english": "Kihunde",
    "wfZid": "Z1928"
  },
  {
    "iso": "sjd",
    "native": "Kildin Sami",
    "english": "Kildin Sami",
    "wfZid": "Z1042"
  },
  {
    "iso": "bkm",
    "native": "Kom",
    "english": "Kom",
    "wfZid": "Z1795"
  },
  {
    "iso": "kfo",
    "native": "Koro Maninka",
    "english": "Koro Maninka",
    "wfZid": "Z1494"
  },
  {
    "iso": "kos",
    "native": "Kosraean",
    "english": "Kosraean",
    "wfZid": "Z1524"
  },
  {
    "iso": "avk",
    "native": "Kotava",
    "english": "Kotava",
    "wfZid": "Z1695"
  },
  {
    "iso": "koy",
    "native": "Koyukon",
    "english": "Koyukon",
    "wfZid": "Z1347"
  },
  {
    "iso": "kpe",
    "native": "Kpelle",
    "english": "Kpelle",
    "wfZid": "Z1432"
  },
  {
    "iso": "kri",
    "native": "Krio",
    "english": "Krio",
    "wfZid": "Z1740"
  },
  {
    "iso": "gcr",
    "native": "kriyòl gwiyannen",
    "english": "Guianan Creole",
    "wfZid": "Z1101"
  },
  {
    "iso": "ku-latn",
    "native": "kurdî (latînî)‎",
    "english": "Kurdish (Latin script)",
    "wfZid": "Z1786"
  },
  {
    "iso": "kus",
    "native": "Kusaal",
    "english": "Kusaal",
    "wfZid": "Z1883"
  },
  {
    "iso": "kj",
    "native": "Kwanyama",
    "english": "Kuanyama",
    "wfZid": "Z1255"
  },
  {
    "iso": "nmg",
    "native": "Kwasio",
    "english": "Kwasio",
    "wfZid": "Z1390"
  },
  {
    "iso": "acf",
    "native": "Kwéyòl Sent Lisi",
    "english": "Saint Lucian Creole",
    "wfZid": "Z1937"
  },
  {
    "iso": "quc",
    "native": "Kʼicheʼ",
    "english": "Kʼicheʼ",
    "wfZid": "Z1243"
  },
  {
    "iso": "jbo",
    "native": "la .lojban.",
    "english": "Lojban",
    "wfZid": "Z1250"
  },
  {
    "iso": "lah",
    "native": "Lahnda",
    "english": "Lahnda",
    "wfZid": "Z1307"
  },
  {
    "iso": "lns",
    "native": "Lamnso'",
    "english": "Lamnso'",
    "wfZid": "Z1779"
  },
  {
    "iso": "lag",
    "native": "Langi",
    "english": "Langi",
    "wfZid": "Z1828"
  },
  {
    "iso": "lv",
    "native": "latviešu",
    "english": "Latvian",
    "wfZid": "Z1709"
  },
  {
    "iso": "to",
    "native": "lea faka-Tonga",
    "english": "Tongan",
    "wfZid": "Z1034"
  },
  {
    "iso": "laj",
    "native": "Lëblaŋo",
    "english": "Lango",
    "wfZid": "Z1940"
  },
  {
    "iso": "lt",
    "native": "lietuvių",
    "english": "Lithuanian",
    "wfZid": "Z1447"
  },
  {
    "iso": "olo",
    "native": "livvinkarjala",
    "english": "Livvi-Karelian",
    "wfZid": "Z1784"
  },
  {
    "iso": "lou",
    "native": "Louisiana Creole",
    "english": "Louisiana Creole",
    "wfZid": "Z1103"
  },
  {
    "iso": "lu",
    "native": "Luba-Katanga",
    "english": "Luba-Katanga",
    "wfZid": "Z1535"
  },
  {
    "iso": "lui",
    "native": "Luiseno",
    "english": "Luiseno",
    "wfZid": "Z1427"
  },
  {
    "iso": "smj",
    "native": "Lule Sami",
    "english": "Lule Sami",
    "wfZid": "Z1354"
  },
  {
    "iso": "lmo",
    "native": "lumbaart",
    "english": "Lombard",
    "wfZid": "Z1452"
  },
  {
    "iso": "lun",
    "native": "Lunda",
    "english": "Lunda",
    "wfZid": "Z1516"
  },
  {
    "iso": "luy",
    "native": "Luyia",
    "english": "Luyia",
    "wfZid": "Z1632"
  },
  {
    "iso": "yua",
    "native": "maaya t’aan",
    "english": "Yucatec Maya",
    "wfZid": "Z1972"
  },
  {
    "iso": "mde",
    "native": "Maba",
    "english": "Maba",
    "wfZid": "Z1077"
  },
  {
    "iso": "jmc",
    "native": "Machame",
    "english": "Machame",
    "wfZid": "Z1629"
  },
  {
    "iso": "maf",
    "native": "Mafa",
    "english": "Mafa",
    "wfZid": "Z1468"
  },
  {
    "iso": "hu-formal",
    "native": "magyar (formal)‎",
    "english": "Hungarian (formal)‎",
    "wfZid": "Z1174"
  },
  {
    "iso": "knn",
    "native": "Maharashtrian Konkani",
    "english": "Maharashtrian Konkani",
    "wfZid": "Z1035"
  },
  {
    "iso": "swb",
    "native": "mahore comorian",
    "english": "mahore comorian",
    "wfZid": "Z1258"
  },
  {
    "iso": "mcp",
    "native": "Makaa",
    "english": "Makaa",
    "wfZid": "Z1203"
  },
  {
    "iso": "mgh",
    "native": "Makhuwa-Meetto",
    "english": "Makhuwa-Meetto",
    "wfZid": "Z1038"
  },
  {
    "iso": "kde",
    "native": "Makonde",
    "english": "Makonde",
    "wfZid": "Z1770"
  },
  {
    "iso": "tog",
    "native": "Malawian Tonga",
    "english": "Malawian Tonga",
    "wfZid": "Z1484"
  },
  {
    "iso": "ms-arab",
    "native": "Malay (Jawi script)",
    "english": "Malay (Jawi script)",
    "wfZid": "Z1434"
  },
  {
    "iso": "mid",
    "native": "Mandaic",
    "english": "Mandaic",
    "wfZid": "Z1526"
  },
  {
    "iso": "man",
    "native": "Mandingo",
    "english": "Mandingo",
    "wfZid": "Z1848"
  },
  {
    "iso": "mnc-latn",
    "native": "manju gisun",
    "english": "Manchu (Latin script)",
    "wfZid": "Z1914"
  },
  {
    "iso": "mrh",
    "native": "Mara",
    "english": "Mara",
    "wfZid": "Z1567"
  },
  {
    "iso": "mrt",
    "native": "Marghi",
    "english": "Margi",
    "wfZid": "Z1967"
  },
  {
    "iso": "chm",
    "native": "Mari",
    "english": "Mari",
    "wfZid": "Z1493"
  },
  {
    "iso": "rwr",
    "native": "Marwari (India)",
    "english": "Marwari (India)",
    "wfZid": "Z1644"
  },
  {
    "iso": "fit",
    "native": "meänkieli",
    "english": "Tornedalen Finnish",
    "wfZid": "Z1681"
  },
  {
    "iso": "byv",
    "native": "Medumba",
    "english": "Medumba",
    "wfZid": "Z1143"
  },
  {
    "iso": "ruq-grek",
    "native": "Megleno-Romanian (Greek script)",
    "english": "Megleno-Romanian (Greek script)",
    "wfZid": "Z1542"
  },
  {
    "iso": "men",
    "native": "Mende",
    "english": "Mende",
    "wfZid": "Z1568"
  },
  {
    "iso": "mer",
    "native": "Meru",
    "english": "Meru",
    "wfZid": "Z1377"
  },
  {
    "iso": "mgo",
    "native": "Metaʼ",
    "english": "Metaʼ",
    "wfZid": "Z1839"
  },
  {
    "iso": "es-mx",
    "native": "Mexican Spanish",
    "english": "Mexican Spanish",
    "wfZid": "Z1133"
  },
  {
    "iso": "crg",
    "native": "Michif",
    "english": "Michif",
    "wfZid": "Z1971"
  },
  {
    "iso": "gmh",
    "native": "Middle High German",
    "english": "Middle High German",
    "wfZid": "Z1794"
  },
  {
    "iso": "mwl",
    "native": "Mirandés",
    "english": "Mirandese",
    "wfZid": "Z1465"
  },
  {
    "iso": "bqz",
    "native": "Mka'a",
    "english": "Mka'a",
    "wfZid": "Z1112"
  },
  {
    "iso": "moh",
    "native": "Mohawk",
    "english": "Mohawk",
    "wfZid": "Z1172"
  },
  {
    "iso": "ro-md",
    "native": "Moldavian",
    "english": "Moldavian",
    "wfZid": "Z1239"
  },
  {
    "iso": "lol",
    "native": "Mongo",
    "english": "Mongo",
    "wfZid": "Z1654"
  },
  {
    "iso": "mua",
    "native": "Mundang",
    "english": "Mundang",
    "wfZid": "Z1765"
  },
  {
    "iso": "umu",
    "native": "Munsee",
    "english": "Munsee",
    "wfZid": "Z1459"
  },
  {
    "iso": "mus",
    "native": "Mvskoke",
    "english": "Muscogee",
    "wfZid": "Z1301"
  },
  {
    "iso": "gmy",
    "native": "Mycenaean Greek",
    "english": "Mycenaean Greek",
    "wfZid": "Z1538"
  },
  {
    "iso": "mye",
    "native": "Myene",
    "english": "Myene",
    "wfZid": "Z1454"
  },
  {
    "iso": "nsk",
    "native": "Naskapi",
    "english": "Naskapi",
    "wfZid": "Z1546"
  },
  {
    "iso": "nmz",
    "native": "nawdm",
    "english": "Nawdm",
    "wfZid": "Z1869"
  },
  {
    "iso": "nnz",
    "native": "Ndaʼndaʼ",
    "english": "Ndaʼndaʼ",
    "wfZid": "Z1248"
  },
  {
    "iso": "cr",
    "native": "Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ",
    "english": "Cree",
    "wfZid": "Z1115"
  },
  {
    "iso": "nge",
    "native": "Ngémba",
    "english": "Ngémba",
    "wfZid": "Z1050"
  },
  {
    "iso": "nnh",
    "native": "Ngiemboon",
    "english": "Ngiemboon",
    "wfZid": "Z1713"
  },
  {
    "iso": "jgo",
    "native": "Ngomba",
    "english": "Ngomba",
    "wfZid": "Z1720"
  },
  {
    "iso": "nla",
    "native": "Ngombala",
    "english": "Ngombala",
    "wfZid": "Z1704"
  },
  {
    "iso": "pcm",
    "native": "Nigerian Pidgin",
    "english": "Nigerian Pidgin",
    "wfZid": "Z1232"
  },
  {
    "iso": "zmi",
    "native": "Nismilan",
    "english": "Negeri Sembilan Malay",
    "wfZid": "Z1939"
  },
  {
    "iso": "nog",
    "native": "Nogai",
    "english": "Nogai",
    "wfZid": "Z1604"
  },
  {
    "iso": "lem",
    "native": "Nomaande",
    "english": "Nomaande",
    "wfZid": "Z1677"
  },
  {
    "iso": "frr",
    "native": "Nordfriisk",
    "english": "Northern Frisian",
    "wfZid": "Z1650"
  },
  {
    "iso": "nn",
    "native": "norsk nynorsk",
    "english": "Norwegian Nynorsk",
    "wfZid": "Z1276"
  },
  {
    "iso": "nod",
    "native": "Northern Thai",
    "english": "Northern Thai",
    "wfZid": "Z1291"
  },
  {
    "iso": "nus",
    "native": "Nuer",
    "english": "Nuer",
    "wfZid": "Z1793"
  },
  {
    "iso": "yas",
    "native": "Nugunu",
    "english": "Nugunu",
    "wfZid": "Z1236"
  },
  {
    "iso": "nup",
    "native": "Nupe",
    "english": "Nupe",
    "wfZid": "Z1919"
  },
  {
    "iso": "nys",
    "native": "Nyunga",
    "english": "Nyungar",
    "wfZid": "Z1864"
  },
  {
    "iso": "ood",
    "native": "O'odham",
    "english": "O'odham",
    "wfZid": "Z1391"
  },
  {
    "iso": "ann",
    "native": "Obolo",
    "english": "Obolo",
    "wfZid": "Z1888"
  },
  {
    "iso": "oc",
    "native": "occitan",
    "english": "Occitan",
    "wfZid": "Z1059"
  },
  {
    "iso": "uz-latn",
    "native": "oʻzbekcha",
    "english": "Uzbek (Latin script)",
    "wfZid": "Z1439"
  },
  {
    "iso": "uz",
    "native": "oʻzbekcha/ўзбекча",
    "english": "Uzbek",
    "wfZid": "Z1120"
  },
  {
    "iso": "oj",
    "native": "Ojibwa",
    "english": "Ojibwa",
    "wfZid": "Z1091"
  },
  {
    "iso": "ojb",
    "native": "Ojibwe",
    "english": "Northwestern Ojibwe",
    "wfZid": "Z1477"
  },
  {
    "iso": "fro",
    "native": "Old French",
    "english": "Old French",
    "wfZid": "Z1499"
  },
  {
    "iso": "goh",
    "native": "Old High German",
    "english": "Old High German",
    "wfZid": "Z1380"
  },
  {
    "iso": "sga",
    "native": "Old Irish",
    "english": "Old Irish",
    "wfZid": "Z1802"
  },
  {
    "iso": "ojp",
    "native": "Old Japanese",
    "english": "Old Japanese",
    "wfZid": "Z1386"
  },
  {
    "iso": "ojp-hira",
    "native": "Old Japanese (Hiragana script)",
    "english": "Old Japanese (Hiragana script)",
    "wfZid": "Z1275"
  },
  {
    "iso": "ojp-hani",
    "native": "Old Japanese (Kanji script)",
    "english": "Old Japanese (Kanji script)",
    "wfZid": "Z1601"
  },
  {
    "iso": "non-runr",
    "native": "Old Norse (Runic script)",
    "english": "Old Norse (Runic script)",
    "wfZid": "Z1261"
  },
  {
    "iso": "pro",
    "native": "Old Provençal",
    "english": "Old Provençal",
    "wfZid": "Z1064"
  },
  {
    "iso": "otk",
    "native": "Old Turkish",
    "english": "Old Turkish",
    "wfZid": "Z1769"
  },
  {
    "iso": "osa",
    "native": "Osage",
    "english": "Osage",
    "wfZid": "Z1727"
  },
  {
    "iso": "hz",
    "native": "Otsiherero",
    "english": "Herero",
    "wfZid": "Z1400"
  },
  {
    "iso": "pal",
    "native": "Pahlavi",
    "english": "Pahlavi",
    "wfZid": "Z1065"
  },
  {
    "iso": "pwn",
    "native": "Paiwan",
    "english": "Paiwan",
    "wfZid": "Z1116"
  },
  {
    "iso": "pau",
    "native": "Palauan",
    "english": "Palauan",
    "wfZid": "Z1252"
  },
  {
    "iso": "pi-sidd",
    "native": "Pali (Siddham script)",
    "english": "Pali (Siddham script)",
    "wfZid": "Z1760"
  },
  {
    "iso": "pag",
    "native": "Pangasinan",
    "english": "Pangasinan",
    "wfZid": "Z1502"
  },
  {
    "iso": "pap-aw",
    "native": "Papiamento (Aruba)",
    "english": "Papiamento (Aruba)",
    "wfZid": "Z1446"
  },
  {
    "iso": "pap",
    "native": "Papiamentu",
    "english": "Papiamento",
    "wfZid": "Z1137"
  },
  {
    "iso": "ppu",
    "native": "Papora-Hoanya",
    "english": "Papora-Hoanya",
    "wfZid": "Z1490"
  },
  {
    "iso": "uun",
    "native": "Pazeh",
    "english": "Pazeh",
    "wfZid": "Z1788"
  },
  {
    "iso": "phn",
    "native": "Phoenician",
    "english": "Phoenician",
    "wfZid": "Z1244"
  },
  {
    "iso": "phn-latn",
    "native": "Phoenician (Latin script)",
    "english": "Phoenician (Latin script)",
    "wfZid": "Z1721"
  },
  {
    "iso": "phn-phnx",
    "native": "Phoenician (Phoenician script)",
    "english": "Phoenician (Phoenician script)",
    "wfZid": "Z1670"
  },
  {
    "iso": "pcd",
    "native": "Picard",
    "english": "Picard",
    "wfZid": "Z1829"
  },
  {
    "iso": "piu",
    "native": "Pintupi-Luritja",
    "english": "Pintupi-Luritja",
    "wfZid": "Z1910"
  },
  {
    "iso": "cpx-latn",
    "native": "Pó-sing-gṳ̂ (Hing-hua̍ Báⁿ-uā-ci̍)",
    "english": "Puxian (Latin script)",
    "wfZid": "Z1906"
  },
  {
    "iso": "pon",
    "native": "Pohnpeian",
    "english": "Pohnpeian",
    "wfZid": "Z1240"
  },
  {
    "iso": "fvr",
    "native": "poor’íŋ belé’ŋ",
    "english": "Fur",
    "wfZid": "Z1956"
  },
  {
    "iso": "fuf",
    "native": "Pular",
    "english": "Pular",
    "wfZid": "Z1178"
  },
  {
    "iso": "xpu",
    "native": "Punic",
    "english": "Punic",
    "wfZid": "Z1744"
  },
  {
    "iso": "rm-puter",
    "native": "Putèr",
    "english": "Putèr",
    "wfZid": "Z1373"
  },
  {
    "iso": "pyu",
    "native": "Puyuma",
    "english": "Puyuma",
    "wfZid": "Z1781"
  },
  {
    "iso": "kk-latn",
    "native": "qazaqşa (latın)‎",
    "english": "Kazakh (Latin script)",
    "wfZid": "Z1418"
  },
  {
    "iso": "kk-tr",
    "native": "qazaqşa (Türkïya)‎",
    "english": "Kazakh (Turkey)",
    "wfZid": "Z1070"
  },
  {
    "iso": "crh",
    "native": "qırımtatarca",
    "english": "Crimean Tatar",
    "wfZid": "Z1046"
  },
  {
    "iso": "crh-latn",
    "native": "qırımtatarca (Latin)‎",
    "english": "Crimean Tatar (Latin script)",
    "wfZid": "Z1126"
  },
  {
    "iso": "rah",
    "native": "Rabha",
    "english": "Rabha",
    "wfZid": "Z1324"
  },
  {
    "iso": "rap",
    "native": "Rapanui",
    "english": "Rapanui",
    "wfZid": "Z1090"
  },
  {
    "iso": "ty",
    "native": "reo tahiti",
    "english": "Tahitian",
    "wfZid": "Z1856"
  },
  {
    "iso": "rof",
    "native": "Rombo",
    "english": "Rombo",
    "wfZid": "Z1043"
  },
  {
    "iso": "rtm",
    "native": "Rotuman",
    "english": "Rotuman",
    "wfZid": "Z1649"
  },
  {
    "iso": "rug",
    "native": "Roviana",
    "english": "Roviana",
    "wfZid": "Z1416"
  },
  {
    "iso": "rm-rumgr",
    "native": "Rumantsch Grischun",
    "english": "Rumantsch Grischun",
    "wfZid": "Z1768"
  },
  {
    "iso": "ssy",
    "native": "Saho",
    "english": "Saho",
    "wfZid": "Z1753"
  },
  {
    "iso": "xsy",
    "native": "saisiyat",
    "english": "Saisiyat",
    "wfZid": "Z1214"
  },
  {
    "iso": "szy",
    "native": "Sakizaya",
    "english": "Sakizaya",
    "wfZid": "Z1247"
  },
  {
    "iso": "saq",
    "native": "Samburu",
    "english": "Samburu",
    "wfZid": "Z1022"
  },
  {
    "iso": "sad",
    "native": "Sandawe",
    "english": "Sandawe",
    "wfZid": "Z1615"
  },
  {
    "iso": "sg",
    "native": "Sängö",
    "english": "Sango",
    "wfZid": "Z1469"
  },
  {
    "iso": "sbp",
    "native": "Sangu",
    "english": "Sangu",
    "wfZid": "Z1754"
  },
  {
    "iso": "sa-sidd",
    "native": "Sanskrit (Siddham script)",
    "english": "Sanskrit (Siddham script)",
    "wfZid": "Z1479"
  },
  {
    "iso": "saz",
    "native": "Saurashtra",
    "english": "Saurashtra",
    "wfZid": "Z1511"
  },
  {
    "iso": "sli",
    "native": "Schläsch",
    "english": "Lower Silesian",
    "wfZid": "Z1309"
  },
  {
    "iso": "sco",
    "native": "Scots",
    "english": "Scots",
    "wfZid": "Z1861"
  },
  {
    "iso": "trv",
    "native": "Seediq",
    "english": "Taroko",
    "wfZid": "Z1610"
  },
  {
    "iso": "stq",
    "native": "Seeltersk",
    "english": "Saterland Frisian",
    "wfZid": "Z1598"
  },
  {
    "iso": "see",
    "native": "Seneca",
    "english": "Seneca",
    "wfZid": "Z1840"
  },
  {
    "iso": "nso",
    "native": "Sesotho sa Leboa",
    "english": "Northern Sotho",
    "wfZid": "Z1456"
  },
  {
    "iso": "shy-arab",
    "native": "Shawiya (Arabic script)",
    "english": "Shawiya (Arabic script)",
    "wfZid": "Z1507"
  },
  {
    "iso": "shy-tfng",
    "native": "Shawiya (Tifinagh script)",
    "english": "Shawiya (Tifinagh script)",
    "wfZid": "Z1056"
  },
  {
    "iso": "sid",
    "native": "Sidamo",
    "english": "Sidamo",
    "wfZid": "Z1683"
  },
  {
    "iso": "en-simple",
    "native": "Simple English",
    "english": "Simple English",
    "wfZid": "Z1124"
  },
  {
    "iso": "fos",
    "native": "Siraya",
    "english": "Siraya",
    "wfZid": "Z1666"
  },
  {
    "iso": "srq",
    "native": "Sirionó",
    "english": "Sirionó",
    "wfZid": "Z1611"
  },
  {
    "iso": "sms",
    "native": "Skolt Sami",
    "english": "Skolt Sami",
    "wfZid": "Z1646"
  },
  {
    "iso": "sk",
    "native": "slovenčina",
    "english": "Slovak",
    "wfZid": "Z1488"
  },
  {
    "iso": "sl",
    "native": "slovenščina",
    "english": "Slovenian",
    "wfZid": "Z1616"
  },
  {
    "iso": "xog",
    "native": "Soga",
    "english": "Soga",
    "wfZid": "Z1729"
  },
  {
    "iso": "srn",
    "native": "Sranantongo",
    "english": "Sranan Tongo",
    "wfZid": "Z1583"
  },
  {
    "iso": "sr-latn",
    "native": "srpski (latinica)",
    "english": "Serbian (Latin script)",
    "wfZid": "Z1394"
  },
  {
    "iso": "sh-latn",
    "native": "srpskohrvatski (latinica)",
    "english": "Serbo-Croatian (Latin)",
    "wfZid": "Z1669"
  },
  {
    "iso": "rm-surmiran",
    "native": "Surmiran",
    "english": "Surmiran",
    "wfZid": "Z1571"
  },
  {
    "iso": "rm-sursilv",
    "native": "Sursilvan",
    "english": "Sursilvan",
    "wfZid": "Z1200"
  },
  {
    "iso": "sus",
    "native": "Susu",
    "english": "Susu",
    "wfZid": "Z1058"
  },
  {
    "iso": "rm-sutsilv",
    "native": "Sutsilvan",
    "english": "Sutsilvan",
    "wfZid": "Z1824"
  },
  {
    "iso": "fr-ch",
    "native": "Swiss French",
    "english": "Swiss French",
    "wfZid": "Z1757"
  },
  {
    "iso": "shy-latn",
    "native": "tacawit",
    "english": "Shawiya (Latin script)",
    "wfZid": "Z1691"
  },
  {
    "iso": "shy",
    "native": "tacawit",
    "english": "Shawiya",
    "wfZid": "Z1026"
  },
  {
    "iso": "shi-latn",
    "native": "Taclḥit",
    "english": "Tachelhit (Latin script)",
    "wfZid": "Z1404"
  },
  {
    "iso": "shi",
    "native": "Taclḥit",
    "english": "Tachelhit",
    "wfZid": "Z1540"
  },
  {
    "iso": "dav",
    "native": "Taita",
    "english": "Taita",
    "wfZid": "Z1167"
  },
  {
    "iso": "tzl",
    "native": "Talossan",
    "english": "Talossan",
    "wfZid": "Z1163"
  },
  {
    "iso": "zgh-latn",
    "native": "tamaziɣt tanawayt",
    "english": "Moroccan Amazigh (Latin script)",
    "wfZid": "Z1229"
  },
  {
    "iso": "kab",
    "native": "Taqbaylit",
    "english": "Kabyle",
    "wfZid": "Z1687"
  },
  {
    "iso": "twq",
    "native": "Tasawaq",
    "english": "Tasawaq",
    "wfZid": "Z1811"
  },
  {
    "iso": "tt-latn",
    "native": "tatarça",
    "english": "Tatar (Latin script)",
    "wfZid": "Z1807"
  },
  {
    "iso": "tay",
    "native": "Tayal",
    "english": "Tayal",
    "wfZid": "Z1102"
  },
  {
    "iso": "sjt",
    "native": "Ter Sámi",
    "english": "Ter Sámi",
    "wfZid": "Z1748"
  },
  {
    "iso": "teo",
    "native": "Teso",
    "english": "Teso",
    "wfZid": "Z1176"
  },
  {
    "iso": "taq-latn",
    "native": "təmajəq",
    "english": "Tamasheq (Latin script)",
    "wfZid": "Z1897"
  },
  {
    "iso": "ssf",
    "native": "Thao",
    "english": "Thao",
    "wfZid": "Z1596"
  },
  {
    "iso": "vi",
    "native": "Tiếng Việt",
    "english": "Vietnamese",
    "wfZid": "Z1048"
  },
  {
    "iso": "tem",
    "native": "Timne",
    "english": "Timne",
    "wfZid": "Z1545"
  },
  {
    "iso": "tlh",
    "native": "tlhIngan Hol",
    "english": "Klingon",
    "wfZid": "Z1534"
  },
  {
    "iso": "tlb",
    "native": "Tobelo",
    "english": "Tobelo",
    "wfZid": "Z1136"
  },
  {
    "iso": "tg-latn",
    "native": "tojikī",
    "english": "Tajik (Latin script)",
    "wfZid": "Z1761"
  },
  {
    "iso": "rmg",
    "native": "Traveller Norwegian",
    "english": "Traveller Norwegian",
    "wfZid": "Z1161"
  },
  {
    "iso": "ve",
    "native": "Tshivenda",
    "english": "Venda",
    "wfZid": "Z1121"
  },
  {
    "iso": "tsi",
    "native": "Tsimshian",
    "english": "Tsimshian",
    "wfZid": "Z1656"
  },
  {
    "iso": "bag",
    "native": "Tuki",
    "english": "Tuki",
    "wfZid": "Z1783"
  },
  {
    "iso": "tvu",
    "native": "Tunen",
    "english": "Tunen",
    "wfZid": "Z1433"
  },
  {
    "iso": "lcm",
    "native": "Tungag",
    "english": "Tungag",
    "wfZid": "Z1565"
  },
  {
    "iso": "aeb-latn",
    "native": "Tûnsî",
    "english": "Tunisian Arabic (Latin script)",
    "wfZid": "Z1708"
  },
  {
    "iso": "tk",
    "native": "Türkmençe",
    "english": "Turkmen",
    "wfZid": "Z1797"
  },
  {
    "iso": "tvl",
    "native": "Tuvalu",
    "english": "Tuvalu",
    "wfZid": "Z1739"
  },
  {
    "iso": "tw",
    "native": "Twi",
    "english": "Twi",
    "wfZid": "Z1344"
  },
  {
    "iso": "umb",
    "native": "Umbundu",
    "english": "Umbundu",
    "wfZid": "Z1308"
  },
  {
    "iso": "ug-latn",
    "native": "Uyghurche",
    "english": "Uyghur (Latin script)",
    "wfZid": "Z1414"
  },
  {
    "iso": "za",
    "native": "Vahcuengh",
    "english": "Zhuang",
    "wfZid": "Z1140"
  },
  {
    "iso": "vai",
    "native": "Vai",
    "english": "Vai",
    "wfZid": "Z1030"
  },
  {
    "iso": "rm-vallader",
    "native": "Vallader",
    "english": "Vallader",
    "wfZid": "Z1655"
  },
  {
    "iso": "ruq",
    "native": "vlăheşte",
    "english": "Megleno-Romanian",
    "wfZid": "Z1273"
  },
  {
    "iso": "ruq-latn",
    "native": "Vlăheşte",
    "english": "Megleno-Romanian (Latin script)",
    "wfZid": "Z1634"
  },
  {
    "iso": "vo",
    "native": "Volapük",
    "english": "Volapük",
    "wfZid": "Z1370"
  },
  {
    "iso": "vun",
    "native": "Vunjo",
    "english": "Vunjo",
    "wfZid": "Z1180"
  },
  {
    "iso": "vut",
    "native": "Vute",
    "english": "Vute",
    "wfZid": "Z1819"
  },
  {
    "iso": "wa",
    "native": "walon",
    "english": "Walloon",
    "wfZid": "Z1764"
  },
  {
    "iso": "wae",
    "native": "Walser",
    "english": "Walser",
    "wfZid": "Z1270"
  },
  {
    "iso": "wbp",
    "native": "Warlpiri",
    "english": "Warlpiri",
    "wfZid": "Z1393"
  },
  {
    "iso": "guc",
    "native": "wayuunaiki",
    "english": "Wayuu",
    "wfZid": "Z1686"
  },
  {
    "iso": "rmw",
    "native": "Welsh-Romani",
    "english": "Welsh-Romani",
    "wfZid": "Z1256"
  },
  {
    "iso": "cja",
    "native": "Western Cham",
    "english": "Western Cham",
    "wfZid": "Z1842"
  },
  {
    "iso": "cja-arab",
    "native": "Western Cham (Arabic script)",
    "english": "Western Cham (Arabic script)",
    "wfZid": "Z1522"
  },
  {
    "iso": "cja-cham",
    "native": "Western Cham (Cham script)",
    "english": "Western Cham (Cham script)",
    "wfZid": "Z1327"
  },
  {
    "iso": "cja-latn",
    "native": "Western Cham (Latin script)",
    "english": "Western Cham (Latin script)",
    "wfZid": "Z1548"
  },
  {
    "iso": "wo",
    "native": "Wolof",
    "english": "Wolof",
    "wfZid": "Z1772"
  },
  {
    "iso": "hsn",
    "native": "Xiang",
    "english": "Xiang",
    "wfZid": "Z1129"
  },
  {
    "iso": "ts",
    "native": "Xitsonga",
    "english": "Tsonga",
    "wfZid": "Z1636"
  },
  {
    "iso": "yav",
    "native": "Yangben",
    "english": "Yangben",
    "wfZid": "Z1862"
  },
  {
    "iso": "yao",
    "native": "Yao",
    "english": "Yao",
    "wfZid": "Z1242"
  },
  {
    "iso": "yap",
    "native": "Yapese",
    "english": "Yapese",
    "wfZid": "Z1249"
  },
  {
    "iso": "ybb",
    "native": "Yemba",
    "english": "Yemba",
    "wfZid": "Z1810"
  },
  {
    "iso": "knc",
    "native": "Yerwa Kanuri",
    "english": "Yerwa Kanuri",
    "wfZid": "Z1949"
  },
  {
    "iso": "zap",
    "native": "Zapotec",
    "english": "Zapotec",
    "wfZid": "Z1575"
  },
  {
    "iso": "sgs",
    "native": "žemaitėška",
    "english": "Samogitian",
    "wfZid": "Z1755"
  },
  {
    "iso": "gbz",
    "native": "Zoroastrian Dari",
    "english": "Zoroastrian Dari",
    "wfZid": "Z1135"
  },
  {
    "iso": "el",
    "native": "ελληνικά",
    "english": "Greek",
    "wfZid": "Z1827"
  },
  {
    "iso": "pnt",
    "native": "Ποντιακά",
    "english": "Pontic",
    "wfZid": "Z1652"
  },
  {
    "iso": "ady-cyrl",
    "native": "адыгабзэ",
    "english": "Adyghe (Cyrillic script)",
    "wfZid": "Z1475"
  },
  {
    "iso": "ady",
    "native": "адыгабзэ",
    "english": "Adyghe",
    "wfZid": "Z1195"
  },
  {
    "iso": "kbd-cyrl",
    "native": "Адыгэбзэ",
    "english": "Kabardian (Cyrillic script)",
    "wfZid": "Z1290"
  },
  {
    "iso": "alt",
    "native": "алтай тил",
    "english": "Southern Altai",
    "wfZid": "Z1746"
  },
  {
    "iso": "ba",
    "native": "башҡортса",
    "english": "Bashkir",
    "wfZid": "Z1211"
  },
  {
    "iso": "bxr",
    "native": "буряад",
    "english": "Buryat (Russia) ",
    "wfZid": "Z1417"
  },
  {
    "iso": "bg",
    "native": "български",
    "english": "Bulgarian",
    "wfZid": "Z1823"
  },
  {
    "iso": "ruq-cyrl",
    "native": "Влахесте",
    "english": "Megleno-Romanian (Cyrillic script)",
    "wfZid": "Z1584"
  },
  {
    "iso": "dlg",
    "native": "долган тыла",
    "english": "Dolgan",
    "wfZid": "Z1973"
  },
  {
    "iso": "crh-ro",
    "native": "къырымтатарджа (tatarşa)",
    "english": "Crimean Tatar (Romania)",
    "wfZid": "Z1891"
  },
  {
    "iso": "crh-cyrl",
    "native": "къырымтатарджа (Кирилл)‎",
    "english": "Crimean Tatar (Cyrillic script)",
    "wfZid": "Z1775"
  },
  {
    "iso": "mrj",
    "native": "кырык мары",
    "english": "Western Mari",
    "wfZid": "Z1183"
  },
  {
    "iso": "kk-cyrl",
    "native": "қазақша (кирил)‎",
    "english": "Kazakh (Cyrillic script)",
    "wfZid": "Z1478"
  },
  {
    "iso": "kk-kz",
    "native": "қазақша (Қазақстан)‎",
    "english": "Kazakh (Kazakhstan)",
    "wfZid": "Z1536"
  },
  {
    "iso": "mk",
    "native": "македонски",
    "english": "Macedonian",
    "wfZid": "Z1402"
  },
  {
    "iso": "isv-cyrl",
    "native": "меджусловјанскы",
    "english": "Interslavic (Cyrillic script)",
    "wfZid": "Z1924"
  },
  {
    "iso": "mo",
    "native": "молдовеняскэ",
    "english": "Moldovan",
    "wfZid": "Z1668"
  },
  {
    "iso": "mn",
    "native": "монгол",
    "english": "Mongolian",
    "wfZid": "Z1554"
  },
  {
    "iso": "rut",
    "native": "мыхаӀбишды",
    "english": "Rutul",
    "wfZid": "Z1915"
  },
  {
    "iso": "ce",
    "native": "нохчийн",
    "english": "Chechen",
    "wfZid": "Z1335"
  },
  {
    "iso": "mhr",
    "native": "олык марий",
    "english": "Eastern Mari",
    "wfZid": "Z1160"
  },
  {
    "iso": "rsk",
    "native": "руски",
    "english": "Pannonian Rusyn",
    "wfZid": "Z1874"
  },
  {
    "iso": "cu",
    "native": "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ",
    "english": "Church Slavic",
    "wfZid": "Z1105"
  },
  {
    "iso": "sr-cyrl",
    "native": "српски (ћирилица)",
    "english": "Serbian (Cyrillic script)",
    "wfZid": "Z1181"
  },
  {
    "iso": "sr",
    "native": "српски / srpski",
    "english": "Serbian",
    "wfZid": "Z1158"
  },
  {
    "iso": "sh-cyrl",
    "native": "српскохрватски (ћирилица)",
    "english": "Serbo-Croatian (Cyrillic)",
    "wfZid": "Z1653"
  },
  {
    "iso": "tt-cyrl",
    "native": "татарча",
    "english": "Tatar (Cyrillic script)",
    "wfZid": "Z1724"
  },
  {
    "iso": "tly-cyrl",
    "native": "толыши",
    "english": "Talysh (Cyrillic script)",
    "wfZid": "Z1580"
  },
  {
    "iso": "tg-cyrl",
    "native": "тоҷикӣ",
    "english": "Tajik (Cyrillic script)",
    "wfZid": "Z1737"
  },
  {
    "iso": "uz-cyrl",
    "native": "ўзбекча",
    "english": "Uzbek (Cyrillic script)",
    "wfZid": "Z1474"
  },
  {
    "iso": "xal",
    "native": "хальмг",
    "english": "Kalmyk",
    "wfZid": "Z1100"
  },
  {
    "iso": "ug-arab",
    "native": "ئۇيغۇرچە",
    "english": "Uyghur (Arabic script)",
    "wfZid": "Z1279"
  },
  {
    "iso": "ayh",
    "native": "الحضرمية",
    "english": "Hadhrami Arabic",
    "wfZid": "Z1976"
  },
  {
    "iso": "acq",
    "native": "تعزية-عدنية",
    "english": "Ta'izzi-Adeni Arabic",
    "wfZid": "Z1894"
  },
  {
    "iso": "trw",
    "native": "توروالی",
    "english": "Torwali",
    "wfZid": "Z1931"
  },
  {
    "iso": "aeb-arab",
    "native": "تونسي",
    "english": "Tunisian Arabic (Arabic script)",
    "wfZid": "Z1633"
  },
  {
    "iso": "bcc",
    "native": "جهلسری بلوچی",
    "english": "Southern Balochi",
    "wfZid": "Z1296"
  },
  {
    "iso": "rhg-arab",
    "native": "رُحَ࣪ڠۡگَ࣪ࢬ عَرࣤبِي لࣦكَ࣪",
    "english": "Rohingya (Arabic script)",
    "wfZid": "Z1979"
  },
  {
    "iso": "bgn",
    "native": "روچ کپتین بلوچی",
    "english": "Western Balochi",
    "wfZid": "Z1505"
  },
  {
    "iso": "ota",
    "native": "عثمانلیجە",
    "english": "Ottoman Turkish",
    "wfZid": "Z1825"
  },
  {
    "iso": "acm",
    "native": "عراقي",
    "english": "Mesopotamian Arabic",
    "wfZid": "Z1889"
  },
  {
    "iso": "kk-arab",
    "native": "قازاقشا (تٴوتە)‏",
    "english": "Kazakh (Arabic script)",
    "wfZid": "Z1699"
  },
  {
    "iso": "kk-cn",
    "native": "قازاقشا (جۇنگو)‏",
    "english": "Kazakh (China)",
    "wfZid": "Z1731"
  },
  {
    "iso": "ks-arab",
    "native": "کٲشُر",
    "english": "Kashmiri (Arabic script)",
    "wfZid": "Z1098"
  },
  {
    "iso": "gju-arab",
    "native": "گوجری",
    "english": "Gojri (Arabic script)",
    "wfZid": "Z1959"
  },
  {
    "iso": "luz",
    "native": "لئری دوٙمینی",
    "english": "Southern Luri",
    "wfZid": "Z1072"
  },
  {
    "iso": "lki",
    "native": "لەکی",
    "english": "Laki",
    "wfZid": "Z1424"
  },
  {
    "iso": "bgc-arab",
    "native": "ہریانوی",
    "english": "Haryanvi (Arabic script)",
    "wfZid": "Z1938"
  },
  {
    "iso": "hno",
    "native": "ہندکو",
    "english": "Hindko",
    "wfZid": "Z1880"
  },
  {
    "iso": "aii",
    "native": "ܣܘܪܝܬ",
    "english": "Suret",
    "wfZid": "Z1930"
  },
  {
    "iso": "nqo",
    "native": "ߒߞߏ",
    "english": "N’Ko",
    "wfZid": "Z1438"
  },
  {
    "iso": "zgh",
    "native": "ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ",
    "english": "Standard Moroccan Tamazight",
    "wfZid": "Z1472"
  },
  {
    "iso": "shi-tfng",
    "native": "ⵜⴰⵛⵍⵃⵉⵜ",
    "english": "Tachelhit (Tifinagh script)",
    "wfZid": "Z1458"
  },
  {
    "iso": "anp",
    "native": "अङ्गिका",
    "english": "Angika",
    "wfZid": "Z1297"
  },
  {
    "iso": "ks-deva",
    "native": "कॉशुर",
    "english": "Kashmiri (Devanagari script)",
    "wfZid": "Z1569"
  },
  {
    "iso": "gju-deva",
    "native": "गुज्जरी",
    "english": "Gojri (Devanagari script)",
    "wfZid": "Z1960"
  },
  {
    "iso": "gom-deva",
    "native": "गोंयची कोंकणी",
    "english": "Goan Konkani (Devanagari script)",
    "wfZid": "Z1353"
  },
  {
    "iso": "gom",
    "native": "गोंयची कोंकणी / Gõychi Konknni",
    "english": "Goan Konkani",
    "wfZid": "Z1850"
  },
  {
    "iso": "dty",
    "native": "डोटेली",
    "english": "Doteli",
    "wfZid": "Z1044"
  },
  {
    "iso": "new",
    "native": "नेपाल भाषा",
    "english": "Newari",
    "wfZid": "Z1553"
  },
  {
    "iso": "ne",
    "native": "नेपाली",
    "english": "Nepali",
    "wfZid": "Z1675"
  },
  {
    "iso": "mai",
    "native": "मैथिली",
    "english": "Maithili",
    "wfZid": "Z1285"
  },
  {
    "iso": "thr",
    "native": "राना थारू",
    "english": "Rana Tharu",
    "wfZid": "Z1957"
  },
  {
    "iso": "kip",
    "native": "शेषी पाङ",
    "english": "Sheshi Kham",
    "wfZid": "Z1951"
  },
  {
    "iso": "pa",
    "native": "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)",
    "english": "Punjabi (Gurmukhi)",
    "wfZid": "Z1657"
  },
  {
    "iso": "gu",
    "native": "ગુજરાતી",
    "english": "Gujarati",
    "wfZid": "Z1696"
  },
  {
    "iso": "dso",
    "native": "ଦେଶିଆ",
    "english": "Desiya",
    "wfZid": "Z1964"
  },
  {
    "iso": "bfw",
    "native": "ରେମସାମ୍",
    "english": "Bonda",
    "wfZid": "Z1958"
  },
  {
    "iso": "wsg",
    "native": "గోండి",
    "english": "Adilabad Gondi",
    "wfZid": "Z1918"
  },
  {
    "iso": "kn",
    "native": "ಕನ್ನಡ",
    "english": "Kannada",
    "wfZid": "Z1549"
  },
  {
    "iso": "tcy",
    "native": "ತುಳು",
    "english": "Tulu",
    "wfZid": "Z1281"
  },
  {
    "iso": "ml",
    "native": "മലയാളം",
    "english": "Malayalam",
    "wfZid": "Z1012"
  },
  {
    "iso": "si",
    "native": "සිංහල",
    "english": "Sinhala",
    "wfZid": "Z1053"
  },
  {
    "iso": "dz",
    "native": "ཇོང་ཁ",
    "english": "Dzongkha",
    "wfZid": "Z1147"
  },
  {
    "iso": "bo",
    "native": "བོད་ཡིག",
    "english": "Tibetan",
    "wfZid": "Z1527"
  },
  {
    "iso": "bug-bugi",
    "native": "ᨅᨔ ᨕᨘᨁᨗ",
    "english": "Buginese (Lontara script)",
    "wfZid": "Z1908"
  },
  {
    "iso": "ksw",
    "native": "စှီၤ",
    "english": "Karen",
    "wfZid": "Z1020"
  },
  {
    "iso": "blk",
    "native": "ပအိုဝ်ႏ",
    "english": "Pa'O",
    "wfZid": "Z1018"
  },
  {
    "iso": "kjp",
    "native": "ဖၠုံလိက်",
    "english": "Eastern Pwo",
    "wfZid": "Z1863"
  },
  {
    "iso": "shn",
    "native": "ၽႃႇသႃႇတႆး ",
    "english": "Shan",
    "wfZid": "Z1392"
  },
  {
    "iso": "mnw",
    "native": "ဘာသာ မန်",
    "english": "Mon",
    "wfZid": "Z1620"
  },
  {
    "iso": "rki",
    "native": "ရခိုင်",
    "english": "Arakanese",
    "wfZid": "Z1528"
  },
  {
    "iso": "rhg-rohg",
    "native": "𐴌𐴟𐴇𐴥𐴝𐴚𐴒𐴙𐴝",
    "english": "Rohingya (Hanifi script)",
    "wfZid": "Z1978"
  },
  {
    "iso": "ccp",
    "native": "𑄌𑄋𑄴𑄟𑄳𑄦",
    "english": "Chakma",
    "wfZid": "Z1374"
  },
  {
    "iso": "tdd",
    "native": "ᥖᥭᥰᥖᥬᥳᥑᥨᥒᥰ",
    "english": "Tai Nuea",
    "wfZid": "Z1875"
  },
  {
    "iso": "ban-bali",
    "native": "ᬩᬲᬩᬮᬶ",
    "english": "Balinese (Balinese script)",
    "wfZid": "Z1821"
  },
  {
    "iso": "mnc-mong",
    "native": "ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ",
    "english": "Manchu (Mongolian script)",
    "wfZid": "Z1913"
  },
  {
    "iso": "sat",
    "native": "ᱥᱟᱱᱛᱟᱲᱤ",
    "english": "Santali",
    "wfZid": "Z1600"
  },
  {
    "iso": "chr",
    "native": "ᏣᎳᎩ",
    "english": "Cherokee",
    "wfZid": "Z1836"
  },
  {
    "iso": "ike-cans",
    "native": "ᐃᓄᒃᑎᑐᑦ",
    "english": "Eastern Canadian (Aboriginal syllabics)",
    "wfZid": "Z1702"
  },
  {
    "iso": "bax-bamu",
    "native": "ꚶꛉ꛰꛲ꚫꛦꚳ",
    "english": "Bamun (Bamu script)",
    "wfZid": "Z1952"
  },
  {
    "iso": "ja-kana",
    "native": "ニホンゴ（カタカナ）",
    "english": "Japanese (Katakana script)",
    "wfZid": "Z1736"
  },
  {
    "iso": "ja-hira",
    "native": "にほんご（ひらがな）",
    "english": "Japanese (Hiragana script)",
    "wfZid": "Z1171"
  },
  {
    "iso": "got",
    "native": "𐌲𐌿𐍄𐌹𐍃𐌺",
    "english": "Gothic",
    "wfZid": "Z1396"
  },
  {
    "iso": "zh-cn",
    "native": "中文（中国大陆）‎",
    "english": "Chinese (China)",
    "wfZid": "Z1411"
  },
  {
    "iso": "zh-sg",
    "native": "中文（新加坡）‎",
    "english": "Chinese (Singapore)",
    "wfZid": "Z1504"
  },
  {
    "iso": "zh-mo",
    "native": "中文（澳門）‎",
    "english": "Chinese (Macau)",
    "wfZid": "Z1406"
  },
  {
    "iso": "zh-tw",
    "native": "中文（臺灣）‎",
    "english": "Chinese (Taiwan)",
    "wfZid": "Z1107"
  },
  {
    "iso": "zh-my",
    "native": "中文（马来西亚）‎",
    "english": "Chinese (Malaysia)",
    "wfZid": "Z1591"
  },
  {
    "iso": "wuu-hant",
    "native": "吳語（正體）",
    "english": "Wu (Traditional Han script)",
    "wfZid": "Z1900"
  },
  {
    "iso": "wuu-hans",
    "native": "吴语（简体）",
    "english": "Wu (Simplified Han script)",
    "wfZid": "Z1899"
  },
  {
    "iso": "hak",
    "native": "客家語 / Hak-kâ-ngî",
    "english": "Hakka",
    "wfZid": "Z1262"
  },
  {
    "iso": "hak-hant",
    "native": "客家語（繁體）",
    "english": "Hakka (Traditional Han script)",
    "wfZid": "Z1933"
  },
  {
    "iso": "hak-hans",
    "native": "客家语（简体）",
    "english": "Hakka (Simplified Han script)",
    "wfZid": "Z1932"
  },
  {
    "iso": "ja-hani",
    "native": "日本語（漢字）",
    "english": "Japanese (Kanji script)",
    "wfZid": "Z1326"
  },
  {
    "iso": "cjy-hant",
    "native": "晉語（正字）",
    "english": "Jin (Traditional Han script)",
    "wfZid": "Z1134"
  },
  {
    "iso": "cjy-hans",
    "native": "晋语（简化字）",
    "english": "Jin (Simplified Han script)",
    "wfZid": "Z1637"
  },
  {
    "iso": "yue",
    "native": "粵語",
    "english": "Cantonese",
    "wfZid": "Z1202"
  },
  {
    "iso": "yue-hant",
    "native": "粵語（繁體）",
    "english": "Cantonese (Traditional Han script)",
    "wfZid": "Z1902"
  },
  {
    "iso": "yue-hans",
    "native": "粵语（简体）",
    "english": "Cantonese (Simplified Han script)",
    "wfZid": "Z1901"
  },
  {
    "iso": "cpx-hant",
    "native": "莆仙語（繁體）",
    "english": "Puxian (Traditional Han script)",
    "wfZid": "Z1904"
  },
  {
    "iso": "cpx-hans",
    "native": "莆仙语（简体）",
    "english": "Puxian (Simplified Han script)",
    "wfZid": "Z1905"
  },
  {
    "iso": "gan-hant",
    "native": "贛語（繁體）‎",
    "english": "Gan (Traditional Han script)",
    "wfZid": "Z1372"
  },
  {
    "iso": "gan-hans",
    "native": "赣语（简体）‎",
    "english": "Gan (Simplified Han script)",
    "wfZid": "Z1375"
  },
  {
    "iso": "nan-hant",
    "native": "閩南語（傳統漢字）",
    "english": "Minnan (Traditional Han script)",
    "wfZid": "Z1892"
  },
  {
    "iso": "nan-hani",
    "native": "閩南語（漢字）/ 闽南语（汉字）",
    "english": "Minnan (Han script)",
    "wfZid": "Z1647"
  },
  {
    "iso": "cdo",
    "native": "閩東語 / Mìng-dĕ̤ng-ngṳ̄",
    "english": "Mindong",
    "wfZid": "Z1577"
  },
  {
    "iso": "cdo-hant",
    "native": "閩東語（傳統漢字）",
    "english": "Mindong (Traditional Han script)",
    "wfZid": "Z1954"
  }
];
